name: Publish Python package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write    # ilaina amin’ny OpenID Connect (OIDC)
  contents: read     # ilaina amin’ny fidirana amin’ny code

jobs:
  build-and-publish:
    name: Build and publish package
    runs-on: ubuntu-latest

    environment: pypi   # mitovy amin’ny Environment name napetraka ao amin’ny PyPI

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/